package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("yameriflex")
    void generatedTest() {
        step("open(\"http://www.myameriflex.com/\");", () -> {
            step("// todo: just add selenium action");
        });

        step("$(\".page-hero-action\").click();", () -> {
            step("// todo: just add selenium action");
        });

        step("$(\".page-heading\").shouldHave(text(\"Complete the form below and one of our team members will be in touch with you soon.\"));", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'http://www.myameriflex.com/'", () ->
            open("http://www.myameriflex.com/"));

        step("Page title should have text 'Ameriflex – We Keep Your World Quiet'", () -> {
            String expectedTitle = "Ameriflex – We Keep Your World Quiet";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'http://www.myameriflex.com/'", () ->
            open("http://www.myameriflex.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}